export const FETCH_TODOS_SAGA = 'saga/FETCH_TODOS'
export const ADD_TODO_SAGA = 'saga/ADD_TODO'
export const TOGGLE_DONE_SAGA = 'saga/TOGGLE_DONE'

export const SET_TEXT = 'SET_TEXT'
export const SET_TODOS = 'SET_TODOS'
export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const TOGGLE_DONE = 'TOGGLE_DONE'
export const CLEAR = 'CLEAR'
